{
  "name": "Home Assistant Time Machine",
  "version": "1.0.12",
  "slug": "homeassistant-time-machine",
  "description": "Browse and restore Home Assistant configuration backups.",
  "url": "https://github.com/saihgupr/HomeAssistantTimeMachine",
  "arch": ["amd64", "aarch64"],
  "startup": "application",
  "boot": "auto",
  "init": false,
  "ports": {
    "3000/tcp": 3000
  },
  "ports_description": {
    "3000/tcp": "Web interface"
  },
  "host_network": false,
  "map": [
    "config:rw",
    "media:rw"
  ],
  "webui": "http://[HOST]:[PORT:3000]"
}